name: lightning_network

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow manually'

jobs:
  build:
    runs-on: ubuntu-latest
    # use strategy matrix build images
    strategy:
      matrix:
        image:
          - name: lnd-v0.17.0-beta-alpine
            context: "./lnd/alpine/v0.17.0-beta"
          - name: lnd-v0.17.1-beta-alpine
            context: "./lnd/alpine/v0.17.1-beta"
          - name: lnd-v0.17.3-beta-alpine
            context: "./lnd/alpine/v0.17.3-beta"
          - name: lnd-v0.18.5-beta-alpine
            context: "./lnd/alpine/v0.18.5-beta"
          - name: taproot-assets-v0.3.0-alpha-alpine
            context: "./tapd/alpine/v0.3.0-alpha"
          - name: taproot-assets-v0.3.1-alpha-alpine
            context: "./tapd/alpine/v0.3.1-alpha"
          - name: taproot-assets-v0.3.2-alpha-alpine
            context: "./tapd/alpine/v0.3.2-alpha"
          - name: taproot-assets-v0.5.1-alpha-alpine
            context: "./tapd/alpine/v0.5.1-alpha"
          - name: litd-v0.12.0-alpha-alpine
            context: "./litd/alpine/v0.12.0-alpha"
          - name: litd-v0.12.2-alpha-alpine
            context: "./litd/alpine/v0.12.2-alpha"
          - name: litd-v0.14.1-alpha-alpine
            context: "./litd/alpine/v0.14.1-alpha"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ matrix.image.name }}